### ISSUE TITLE
Jade has been renamed to pug, please install the latest version of pug instead of jade

### ISSUE THREAD

**Issue by sirkitree** [davexoxide/rendervideositemap#3]
https://www.npmjs.com/package/pug

**Comment by davexoxide** [comment]
You think even if we go with #4 that it's worth the effort (if there is any) to continue supporting these templates? I was just trying out something new and it was prepackaged with the version of expressjs that I installed.

With that being said, I do think jade/pug is awesome for prototyping!

**Comment by sirkitree** [comment]
i just tried swapping one for one and got errors - not worth it imho
